spring:
  application:
    name: account-service
server:
  servlet:
    context-path: /accounts
  port: 9100

eureka:
client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
instance:
hostname: localhost

security:
    oauth2:
      resource:
        user-info-uri: http://auth-service:5000/uaa/users/current
      client:
        clientId: account-service
        clientSecret: secret
        accessTokenUri: http://auth-service:5000/uaa/oauth/token
        grant-type: client_credentials
        scope: server

#feign:
#  hystrix:
#    enabled: true

spring.main.allow-bean-definition-overriding: true